// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfyenibrmpnsugvrrbym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeWVuaWJybXBuc3VndnJyYnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzA5NDIsImV4cCI6MjA2NTMwNjk0Mn0.GMhZ-vegqGf69HEFnyXQ0v3r4PPnVpZx4bVkKsk27Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);